#pragma once
void test_insert();
void test_remove();
void test_clear();
void test_find();
void test_find_key();
void test_assignment_operator();
void test_copy_constructor();
void test_print();
void test_get_largest();
void test_get_smallest();
void test_for_each();
void test_word_count();
